spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bigwork?serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: hyf5201314

logging:
  level:
    com.example.preSpring.dao : debug
